// Home page sections — English version

// === SERVICES ===
const Services = () => {
  const services = [
    { icon: "scale", title: "AI Consulting for Business", desc: "Professional consulting on AI implementation: from programming tools (GitHub Copilot, Claude Code), through audio, video and presentation creation, meeting transcriptions, to applications in law, medicine and agriculture. I identify the areas with the greatest automation potential in your industry." },
    { icon: "book", title: "AI Tutoring", desc: "Individual training in artificial intelligence for private individuals. Programming assistants, audio and video generators, transcription apps, industry-specific AI solutions. Whatever your field — I'll help you unlock the potential of AI." },
    { icon: "chart", title: "AI Marketing Automation", desc: "Comprehensive marketing automation powered by AI. Ad copy, social media posts, email campaigns and graphics generated by AI — no manual work required." },
    { icon: "cpu", title: "AI Agents & Process Automation", desc: "Intelligent agents and advanced automation workflows using n8n, Zapier and LangChain. I automate repetitive processes, integrate systems and build autonomous AI agents that handle complex tasks without your involvement." },
    { icon: "bot", title: "Custom AI Assistants", desc: "Design and deployment of dedicated AI assistants tailored to your industry. From customer service automation, through analysis of legal and medical documents, to support in precision agriculture. Full integration with existing systems." },
    { icon: "shield", title: "AI Implementations & NIS2 Compliance", desc: "Comprehensive support in deploying AI solutions compliant with the NIS2 directive. Security audits, cybersecurity procedures, risk management and incident reporting. Meet regulatory requirements while harnessing the potential of AI.", tag: "Flagship", featured: true, href: "/NIS2/" },
  ];

  return (
    <section className="section" id="services">
      <div className="container">
        <div className="section-header">
          <span className="eyebrow">/ Services</span>
          <h2>Our Services</h2>
        </div>
        <div className="grid grid-3">
          {services.map((s, i) => (
            <div key={i} className={`card ${s.featured ? "card-accent" : ""}`}>
              {s.tag && (
                <span className="chip" style={{ marginBottom: 16, color: "var(--accent)", borderColor: "var(--accent)" }}>
                  ★ {s.tag}
                </span>
              )}
              <div style={{ color: "var(--accent)", marginBottom: 16 }}>
                <Icon name={s.icon} size={26} />
              </div>
              <h3 style={{ marginBottom: 12 }}>{s.title}</h3>
              <p className="text-muted" style={{ fontSize: "0.95rem" }}>{s.desc}</p>
              {s.href && (
                <a href={s.href} style={{ display: "inline-flex", alignItems: "center", gap: 6, marginTop: 16, fontSize: "0.875rem", fontWeight: 500 }}>
                  See dedicated page <Icon name="arrow" size={14} />
                </a>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// === PACKAGES ===
const Packages = () => {
  const packs = [
    {
      name: "Start-AI Package",
      icon: "📋",
      features: [
        "Comprehensive diagnosis of company needs",
        "Consulting on local LLM models",
        "Map of processes to automate",
        "Mini-book with practical recommendations",
        "AI implementation roadmap for your organization",
        "Identification of key optimization areas",
      ],
    },
    {
      name: "Fit-AI Package",
      icon: "🎯",
      features: [
        "Personalization of AI tools for your team",
        "Configuration of ChatGPT, Copilot, Claude",
        "Library of ready-to-use prompts",
        "AI security playbook",
        "Team training tailored to your needs",
        "Reusable video recording",
        "Post-implementation support and ongoing optimization",
      ],
      featured: true,
    },
  ];

  return (
    <section className="section" id="packages" style={{ background: "var(--bg-elev)" }}>
      <div className="container">
        <div className="section-header">
          <span className="eyebrow">/ Packages</span>
          <h2>Our Packages</h2>
        </div>
        <div className="grid grid-2">
          {packs.map((p, i) => (
            <div key={i} className={`card ${p.featured ? "card-accent" : ""}`}>
              <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
                <span style={{ fontSize: "1.75rem" }}>{p.icon}</span>
                <h3>{p.name}</h3>
              </div>
              <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 12 }}>
                {p.features.map((f, j) => (
                  <li key={j} style={{ display: "flex", gap: 12, fontSize: "0.95rem", alignItems: "flex-start" }}>
                    <span style={{ color: "var(--accent)", marginTop: 3 }}><Icon name="check" size={14} /></span>
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// === PRICING ===
const Pricing = () => {
  const tiers = [
    {
      name: "AI Tutoring",
      price: "€15",
      note: "per hour (incl. 23% VAT)",
    },
    {
      name: "Start-AI Package",
      price: "€85",
      note: "comprehensive diagnosis (incl. 23% VAT)",
      featured: true,
    },
    {
      name: "Fit-AI Package",
      price: "Custom quote",
      note: "price by arrangement",
      isText: true,
    },
  ];

  return (
    <section className="section" id="pricing">
      <div className="container">
        <div className="section-header">
          <span className="eyebrow">/ Pricing</span>
          <h2>Pricing</h2>
        </div>
        <div className="grid grid-3">
          {tiers.map((t, i) => (
            <div key={i} className={`card ${t.featured ? "card-accent" : ""}`} style={{ display: "flex", flexDirection: "column", textAlign: "center", alignItems: "center" }}>
              <h3 style={{ marginBottom: 20 }}>{t.name}</h3>
              <div style={{ fontSize: t.isText ? "1.5rem" : "2.5rem", fontWeight: 600, letterSpacing: "-0.02em", color: "var(--accent)", marginBottom: 12, lineHeight: 1.1 }}>{t.price}</div>
              <div className="text-muted" style={{ fontSize: "0.9rem", marginBottom: 28, maxWidth: 240 }}>{t.note}</div>
              <a href="#contact" className={`btn ${t.featured ? "btn-accent" : "btn-secondary"}`} style={{ justifyContent: "center", marginTop: "auto" }}>Get in touch<Icon name="arrow" size={14} /></a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// === WEBSITES ===
const WebsitesService = () => (
  <section className="section" id="websites" style={{ background: "var(--bg-elev)" }}>
    <div className="container">
      <div className="section-header">
        <span className="eyebrow">/ Special Service</span>
        <h2>Website Development</h2>
        <p className="text-muted" style={{ fontSize: "1.05rem", maxWidth: 720, margin: "16px auto 0" }}>Professional websites that make your business stand out. Choose the engagement model that suits your needs.</p>
      </div>
      <div className="grid grid-2">
        <div className="card">
          <span className="chip" style={{ marginBottom: 16 }}>Project</span>
          <h3 style={{ marginBottom: 8 }}>Full project delivery</h3>
          <p className="accent" style={{ fontSize: "0.95rem", marginBottom: 16, fontWeight: 500 }}>Finished website + full source code in your hands.</p>
          <p className="text-muted" style={{ marginBottom: 20 }}>
            We design and build your website from scratch using a modern tech stack. On delivery you get the complete source code — no subscriptions, no hidden costs, no lock-in.
          </p>
          <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 10, marginBottom: 24 }}>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>Custom UI/UX design tailored to your brand</span></li>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>Responsive implementation (mobile-first)</span></li>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>Full code ownership — do whatever you want with it</span></li>
          </ul>
          <a href="#contact" className="btn btn-secondary" style={{ justifyContent: "center" }}>Request a quote<Icon name="arrow" size={14} /></a>
        </div>
        <div className="card card-accent">
          <span className="chip" style={{ marginBottom: 16, color: "var(--accent)", borderColor: "var(--accent)" }}>★ Subscription</span>
          <h3 style={{ marginBottom: 8 }}>Full service &amp; CMS</h3>
          <p className="accent" style={{ fontSize: "0.95rem", marginBottom: 16, fontWeight: 500 }}>Edit content in seconds — no coding required.</p>
          <p className="text-muted" style={{ marginBottom: 20 }}>
            Focus on the business, we'll handle the tech. You get an intuitive CMS panel (Sanity.io) where changes to text or images publish instantly. Hosting, maintenance and technical support included.
          </p>
          <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 10, marginBottom: 24 }}>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>CMS panel — edit content without a developer</span></li>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>Instant publishing of live changes</span></li>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>Hosting and domain included in subscription</span></li>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>Ongoing updates and technical support</span></li>
            <li style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: "0.9rem" }}><span className="accent" style={{ marginTop: 2 }}><Icon name="check" size={14} /></span><span>Monthly website performance report</span></li>
          </ul>
          <a href="#contact" className="btn btn-accent" style={{ justifyContent: "center" }}>Choose subscription<Icon name="arrow" size={14} /></a>
        </div>
      </div>
    </div>
  </section>
);

// === WHY US ===
const WhyUs = () => {
  const reasons = [
    { num: "01", icon: "zap", title: "Fast Implementation", desc: "We deploy AI solutions in record time — first results within 7 days." },
    { num: "02", icon: "target", title: "Tailored Solutions", desc: "Every project is adjusted to the specifics of your industry and individual needs." },
    { num: "03", icon: "chart", title: "Measurable Results", desc: "On average a 40% productivity boost and 60% reduction in task completion time." },
    { num: "04", icon: "lock", title: "Data Security", desc: "GDPR-compliant solutions with the highest standards of data protection." },
  ];

  return (
    <section className="section">
      <div className="container">
        <div className="section-header">
          <span className="eyebrow">/ Why BrightMind AI</span>
          <h2>Why BrightMind AI?</h2>
        </div>
        <div className="grid grid-2">
          {reasons.map((r, i) => (
            <div key={i} style={{ display: "flex", gap: 24, padding: "28px 0", borderTop: i < 2 ? "none" : "1px solid var(--border)" }}>
              <div className="mono accent" style={{ fontSize: "0.85rem", letterSpacing: "0.1em", paddingTop: 4, minWidth: 32 }}>{r.num}</div>
              <div>
                <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
                  <span className="accent"><Icon name={r.icon} size={18} /></span>
                  <h3>{r.title}</h3>
                </div>
                <p className="text-muted">{r.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// === PROCESS ===
const Process = () => {
  const steps = [
    { n: "01", title: "🎯 Needs analysis", desc: "I run a detailed analysis of your business processes and identify the areas that will benefit the most from AI automation.", time: "1–2 weeks" },
    { n: "02", title: "📋 Implementation strategy", desc: "I prepare a personalized roadmap with concrete steps, schedule and expected results.", time: "1 week" },
    { n: "03", title: "⚙️ Implementation", desc: "I deploy the selected AI solutions, configure the tools and integrate them with your existing systems.", time: "2–6 weeks" },
    { n: "04", title: "📚 Team training", desc: "I deliver comprehensive training for your team so everyone can use the new AI tools effectively.", time: "1 week" },
    { n: "05", title: "🚀 Support & optimization", desc: "I provide ongoing support, monitor results and optimize solutions to maximize the benefits.", time: "ongoing" },
  ];

  return (
    <section className="section">
      <div className="container">
        <div className="section-header">
          <span className="eyebrow">/ How we work together</span>
          <h2>How does the collaboration process work?</h2>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
          {steps.map((s, i) => (
            <div key={i} style={{ display: "grid", gridTemplateColumns: "80px 1fr 120px", gap: 32, padding: "28px 0", borderTop: "1px solid var(--border)", alignItems: "start" }}>
              <div className="mono" style={{ fontSize: "0.875rem", color: "var(--accent)", letterSpacing: "0.1em" }}>{s.n}</div>
              <div>
                <h3 style={{ marginBottom: 8 }}>{s.title}</h3>
                <p className="text-muted" style={{ maxWidth: 600 }}>{s.desc}</p>
              </div>
              <div className="mono text-dim" style={{ fontSize: "0.825rem", textAlign: "right" }}>{s.time}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// === FAQ ===
const FAQ = () => {
  const [open, setOpen] = React.useState(0);
  const items = [
    { q: "🤖 Will AI replace my employees?", a: "No — AI is designed to support and enhance your employees' capabilities, not replace them. We help automate routine tasks so your team can focus on more creative and strategic work." },
    { q: "💰 How much does it cost to implement AI in my company?", a: "Costs depend on the scale and complexity of the project. The Start-AI package (diagnosis) costs €85, and comprehensive implementations start from €470. We offer a free consultation to discuss your needs and prepare a personalized quote." },
    { q: "⏱️ How long does the implementation take?", a: "A basic implementation takes 1–2 weeks, and comprehensive projects 1–3 months. First results are visible within just a few days. It all depends on the scope of automation and the complexity of processes in your organization." },
    { q: "🔐 Is my data safe?", a: "Absolutely! All our solutions are fully GDPR-compliant. We use local LLM models or secure APIs with the highest security certifications. Your data is never used to train AI models." },
    { q: "📚 Will I get training for my team?", a: "Yes! Every implementation includes comprehensive support for the team. The Fit-AI package contains training tailored to your company's needs, a prompt library and post-implementation support. We also record video instructions for repeated use. We can organize training in various formats — from short workshops to extensive development programs." },
  ];

  return (
    <section className="section">
      <div className="container-narrow">
        <div className="section-header">
          <span className="eyebrow">/ FAQ</span>
          <h2>Frequently Asked Questions</h2>
        </div>
        <div style={{ display: "flex", flexDirection: "column" }}>
          {items.map((item, i) => (
            <div key={i} style={{ borderTop: "1px solid var(--border)", borderBottom: i === items.length - 1 ? "1px solid var(--border)" : "none" }}>
              <button
                onClick={() => setOpen(open === i ? -1 : i)}
                style={{
                  width: "100%",
                  background: "transparent",
                  border: "none",
                  padding: "24px 0",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  cursor: "pointer",
                  color: "var(--fg)",
                  fontFamily: "inherit",
                  fontSize: "1.05rem",
                  fontWeight: 500,
                  textAlign: "left",
                  letterSpacing: "-0.01em",
                }}
              >
                <span>{item.q}</span>
                <span style={{ color: "var(--accent)", fontSize: "1.5rem", lineHeight: 1, transform: open === i ? "rotate(45deg)" : "none", transition: "transform 0.2s" }}>+</span>
              </button>
              {open === i && (
                <div style={{ paddingBottom: 24, color: "var(--fg-muted)", maxWidth: 720 }}>
                  {item.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// === CONTACT ===
const Contact = () => (
  <section className="section" id="contact" style={{ background: "var(--bg-elev)" }}>
    <div className="container">
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 64, alignItems: "start" }}>
        <div>
          <span className="eyebrow">/ Contact</span>
          <h2 style={{ margin: "12px 0 32px" }}>Get in touch</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 16, marginBottom: 32 }}>
            <a href="mailto:kontakt@brightmind-solutions.com" style={{ display: "flex", gap: 16, alignItems: "center", padding: 16, border: "1px solid var(--border)", borderRadius: "var(--radius)", color: "var(--fg)" }}>
              <Icon name="file" />
              <div>
                <div className="text-dim" style={{ fontSize: "0.75rem", textTransform: "uppercase", letterSpacing: "0.1em" }}>Email</div>
                <div>kontakt@brightmind-solutions.com</div>
              </div>
            </a>
            <a href="tel:+48730152161" style={{ display: "flex", gap: 16, alignItems: "center", padding: 16, border: "1px solid var(--border)", borderRadius: "var(--radius)", color: "var(--fg)" }}>
              <Icon name="users" />
              <div>
                <div className="text-dim" style={{ fontSize: "0.75rem", textTransform: "uppercase", letterSpacing: "0.1em" }}>Phone</div>
                <div>+48 730 152 161</div>
              </div>
            </a>
          </div>
          <div className="mono text-dim" style={{ fontSize: "0.8rem" }}>
            Mon–Fri 9:00–17:00 · CET
          </div>
        </div>
        <form
          className="card"
          style={{ padding: 32 }}
          name="contact-en"
          method="POST"
          action="/success/"
          data-netlify="true"
          netlify-honeypot="bot-field"
        >
          <input type="hidden" name="form-name" value="contact-en" />
          <input type="hidden" name="bot-field" />
          <h3 style={{ marginBottom: 24 }}>📬 Contact form</h3>
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            <FormField label="Full name" name="name" required placeholder="John Smith" />
            <FormField label="Email address" name="email" required type="email" placeholder="john@company.com" />
            <FormField label="Phone number" name="phone" type="tel" placeholder="+1 234 567 890" />
            <FormField label="Company name" name="company" placeholder="Company Ltd." />
            <FormSelect label="What is your inquiry about?" name="subject" options={["AI consulting for business", "AI tutoring", "Marketing automation", "AI agents / automation", "Custom AI assistants", "NIS2 implementation", "Website", "Other"]} />
            <FormTextarea label="Project description / additional information" name="message" required placeholder="Describe your needs, expectations and project goals. The more details, the better the tailored offer." />
            <label style={{ display: "flex", gap: 10, fontSize: "0.85rem", color: "var(--fg-muted)", lineHeight: 1.5 }}>
              <input type="checkbox" name="privacy_consent" required style={{ marginTop: 4 }} />
              <span>I agree to the processing of my data in accordance with the <a href="/privacy-policy/">Privacy Policy</a>. *</span>
            </label>
            <label style={{ display: "flex", gap: 10, fontSize: "0.85rem", color: "var(--fg-muted)", lineHeight: 1.5 }}>
              <input type="checkbox" name="marketing_consent" style={{ marginTop: 4 }} />
              <span>I agree to receive marketing information about BrightMind AI Solutions services.</span>
            </label>
            <button type="submit" className="btn btn-primary" style={{ justifyContent: "center", marginTop: 8 }}>Send message 🚀</button>
          </div>
        </form>
      </div>
    </div>
  </section>
);

const FormField = ({ label, required, type = "text", placeholder, name }) => (
  <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
    <span style={{ fontSize: "0.85rem", color: "var(--fg-muted)" }}>{label} {required && <span style={{ color: "var(--accent)" }}>*</span>}</span>
    <input type={type} name={name} placeholder={placeholder} required={required} style={{
      background: "var(--bg)",
      border: "1px solid var(--border)",
      borderRadius: "var(--radius)",
      padding: "12px 14px",
      color: "var(--fg)",
      fontFamily: "inherit",
      fontSize: "0.95rem",
    }} />
  </label>
);

const FormSelect = ({ label, options, name }) => (
  <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
    <span style={{ fontSize: "0.85rem", color: "var(--fg-muted)" }}>{label}</span>
    <select name={name} style={{
      background: "var(--bg)",
      border: "1px solid var(--border)",
      borderRadius: "var(--radius)",
      padding: "12px 14px",
      color: "var(--fg)",
      fontFamily: "inherit",
      fontSize: "0.95rem",
    }}>
      {options.map((o, i) => <option key={i}>{o}</option>)}
    </select>
  </label>
);

const FormTextarea = ({ label, required, placeholder, name }) => (
  <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
    <span style={{ fontSize: "0.85rem", color: "var(--fg-muted)" }}>{label} {required && <span style={{ color: "var(--accent)" }}>*</span>}</span>
    <textarea name={name} placeholder={placeholder} required={required} rows={4} style={{
      background: "var(--bg)",
      border: "1px solid var(--border)",
      borderRadius: "var(--radius)",
      padding: "12px 14px",
      color: "var(--fg)",
      fontFamily: "inherit",
      fontSize: "0.95rem",
      resize: "vertical",
    }}></textarea>
  </label>
);

Object.assign(window, { Services, Packages, Pricing, WebsitesService, WhyUs, Process, FAQ, Contact });
